name: Build Project
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    uses: ragarwal06/deployer-workflow/.github/workflows/build-workflow.yml@main
